server:
  port: 8006
spring:
  application:
    name: "msvc-items"
  cloud:
    discovery:
      client:
        simple:
          instances:
            msvc-products:
              - uri: http://localhost:8004
              - uri: http://localhost:8005
config:
  baseurl:
    endpoint:
      msvc-products: http://msvc-products
