server:
  port: 8006
spring:
  application:
    name: "msvc-items"
#  cloud:
#    discovery:
#      client:
#        simple:
#          instances:
#            msvc-products:
#              - uri: http://localhost:8004
#              - uri: http://localhost:8005
config:
  baseurl:
    endpoint:
      msvc-products: http://msvc-products
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      items:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 3s
    instances:
      items:
        base-config: defecto
